            
version: "3.8"

services:
  flask_app:
    image: flask
    container_name: flask_app
    ports:
      - "8000:8000"
#    networks:
#      - my_network
  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - "6379:6379"
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - redis_insight_volume_data:/db
  
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: ilia
      POSTGRES_PASSWORD: 12345
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ilia53@admin.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
  redis_volume_data:
  redis_insight_volume_data:
  
#networks:
#  my_network:
#    name: my_network
#    driver: bridge